fix compiled on `proc_macro_span_shrink` was removed
        rust-lang/rust/issues/113152

        error[E0635]: unknown feature `proc_macro_span_shrink`
          --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.51/src/lib.rs:92:30
           |
        92 |     feature(proc_macro_span, proc_macro_span_shrink)
           |                              ^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: wineway <wangyuweihx@gmail.com>